# add your desired knowledge graph components here

# protein:
#     represented_as: node
#     preferred_id: uniprot
#     input_label: uniprot_protein

disease:
    represented_as: node
    preferred_id: oncotree
    input_label: Disease
    properties:
        name: str
        shortname: str

study:
    represented_as: node
    input_label: Study
    properties:
        name: str
        description: str
        import_date: str
        pmid: str

patient:
    synonym_for: case
    represented_as: node
    input_label: Patient
    properties:
        unique_patient_key: str

sample:
    is_a: material sample
    represented_as: node
    input_label: Sample
    properties:
        unique_sample_key: str
        sample_type: str

is child of:
    is_a: [association, disease disease association]
    represented_as: edge
    input_label: isChildOf

study disease association:
    is_a: association
    represented_as: edge
    input_label: StudyDiseaseAssociation

has patient:
    is_a: association
    represented_as: edge
    input_label: hasPatient

from patient:
    is_a: association
    represented_as: edge
    input_label: fromPatient